# Catpuccin
# Theme create by: https://github.com/AnshumanNeon
# Update by(sort by time):
# 
# Thanks for all contributor!!

border = "#6c7086"
cursor = "#f5e0dc"
main_background = "#1e1e2e"

terminal_too_small_error = "#c74a4d"
terminal_size_currect = "#4eb8ca"

sidebar_title = "#74c7ec"
sidebar_item = "#a6adc8"
sidebar_selected = "#cba6f7"
sidebar_focus = "#f38ba8"

file_panel_focus = "#b4befe"
file_panel_top_directory_icon = "#a6e3a1"
file_panel_top_path = "#89b5fa"
file_panel_item = "#a6adc8"
file_panel_item_selected = "#9399b2"

footer_focus = "#a6e3a1"

process_bar_gradient = ["#89b4fa", "#a6e3a1", "#eba0ac", "#cba6f7"]
in_operation = "#73c7ec"
done = "#a6e3a1"
fail = "#f38ba8"
cancel = "#eba0ac"

modal_foreground = "#313244"
modal_cancel = "#eba0ac"
modal_confirm = "#89dceb"
