# Ayu Dark
# Theme create by: https://github.com/rustnomicon
# Update by(sort by time):
#
# Thanks for all contributor!!

# If you want to make sidebar border display just set it same as sidebar background color

# Code syntax highlight theme (you can go to https://github.com/alecthomas/chroma/blob/master/styles to find one you like)
code_syntax_highlight = "ayu-dark"

# ========= Border =========
file_panel_border = "#2d2d2d"
sidebar_border = "#1f1f1f"
footer_border = "#2d2d2d"

# ========= Border Active =========
file_panel_border_active = "#ffcc66"
sidebar_border_active = "#ff7733"
footer_border_active = "#aad94c"
modal_border_active = "#5c6773"

# ========= Background (bg) =========
full_screen_bg = "#0f1419"
file_panel_bg = "#0f1419"
sidebar_bg = "#0f1419"
footer_bg = "#0f1419"
modal_bg = "#0f1419"

# ========= Foreground (fg) =========
full_screen_fg = "#b3b1ad"
file_panel_fg = "#b3b1ad"
sidebar_fg = "#b3b1ad"
footer_fg = "#b3b1ad"
modal_fg = "#b3b1ad"

# ========= Special Color =========
cursor = "#ffcc66"
correct = "#aad94c"
error = "#ff3333"
hint = "#36a3d9"
cancel = "#f07178"
# Gradient color can only have two colors!
gradient_color = ["#ffb454", "#36a3d9"]

# ========= File Panel Special Items =========
file_panel_top_directory_icon = "#aad94c"
file_panel_top_path = "#ffcc66"
file_panel_item_selected_fg = "#36a3d9"
file_panel_item_selected_bg = "#0f1419"

# ========= Sidebar Special Items =========
sidebar_title = "#36a3d9"
sidebar_item_selected_fg = "#36a3d9"
sidebar_item_selected_bg = "#0f1419"
sidebar_divider = "#2d2d2d"

# ========= Modal Special Items =========
modal_cancel_fg = "#0f1419"
modal_cancel_bg = "#f07178"

modal_confirm_fg = "#0f1419"
modal_confirm_bg = "#36a3d9"

# ========= Help Menu =========
help_menu_hotkey = "#36a3d9"
help_menu_title = "#f07178"
