# change your theme
theme = "gruvbox"

# useless for now
footer_panel_list = ["processes", "metadata", "clipboard"]


# ==========PLUGINS========== #

# Show more detailed metadata, please install exiftool before enabling this plugin!
metadata = false