name: Go

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.22.2

    - name: Build
      run: |
        go build

    - name: Test
      run: go test ./...
    
    - name: Test `go fmt` creates no diffs
      run: go fmt && git diff --exit-code
