name: Python Testsuite Run

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install -r testsuite/requirements.txt

      - name: Install tmux
        run: sudo apt-get update && sudo apt-get install -y tmux

      - name: Run Tests
        run: python testsuite/main.py
