name: Update gomod2nix.toml
on: [push]

permissions:
 contents: write

jobs:
 dependabot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v26
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Update checksum
        run: |
          cd src
          nix develop --extra-experimental-features "nix-command flakes" '.#' -c "gomod2nix"
          # Commit changes if there's a diff
          if [[ -n $(git diff) ]]; then
            git config --global user.email "107802416+MHNightCat@users.noreply.github.com"
            git config --global user.name "MHNightCat"
            git commit -am "chore: update gomod2nix"
            git push origin HEAD:${{ github.head_ref }}
          fi
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update gomod2nix"
          title: "Update gomod2nix.toml"
          body: "This PR updates the gomod2nix.toml file."
          base: main
